function initPupil
    

    global state gh

    gh.pupil = guihandles(pupil);

    openini('pupil.ini');
    
    % save fields
    state.pupil.settingsFields = {...
        'filePath',...
        'fileName',...
        'fileNumber',...
        'nFrames',...
        'frameRate'...
        };
    state.pupil.saveFields = {...
        'currentFrame',...
        'lidThresh',...
        'pupThresh'...
        };
    state.pupil.eyeSaveFields = {...
        'area',...
        'avg',...
        'majorAxisLength',...
        'minorAxisLength',...
        'centroid'...
        };
    state.pupil.pupilSaveFields = {...
        'area',...
        'diameter',...
        'centroid',...
        'circCenter',...
        'circRadius',...
        'circResidual'...
        };
    
    % set up figures
    state.pupil.frameFigure = ensureFigure('frameFigure', 1);
    % raw frame
    state.pupil.rawFrameAx = subplot(2,2,1); 
    state.pupil.rawFrameImageHandle = imshow(rand(100)*255, [0 255], 'Parent', state.pupil.rawFrameAx);
    state.pupil.eyeBoxHandle = rectangle('Position', [0 0 0 0], 'EdgeColor', 'm');
    set(gca, 'NextPlot', 'add'); %  set intended for update speed    
    % eye frame
    state.pupil.eyeFrameAx = subplot(2,2,2); 
    state.pupil.eyeFrameImageHandle = imshow(rand(100)*255, [0 255], 'Parent', state.pupil.eyeFrameAx);
    state.pupil.pupBoxHandle = rectangle('Position', [0 0 0 0], 'EdgeColor', 'm');    
    set(gca, 'NextPlot', 'add'); %  set intended for update speed            
    % pupil frame
    state.pupil.pupFrameAx = subplot(2,2,3); 
    state.pupil.pupFrameImageHandle = imshow(rand(100)*255, [0 255], 'Parent', state.pupil.pupFrameAx);
    state.pupil.pupCircleHandle = line([0 0], [0 0], 'Parent', state.pupil.pupFrameAx, 'Color', 'y');
    set(gca, 'NextPlot', 'add'); %  set intended for update speed    
    
    set(state.pupil.frameFigure, 'ColorMap', makeColorMap('graySat',8));
    
    
