figSize = [2 1];
saveName = ['phAvg_complete_' animal];
ensureFigure(saveName, 1);
trialSets = {...
    rewardOdorTrials & rewardTrials & ismember(TE.filename, lateSessions),...
    uncuedTrials & rewardTrials & ismember(TE.filename, lateSessions),...
    rewardOdorTrials & ~rewardTrials & ismember(TE.filename, lateSessions)...
    };
[ha, hl] = phPlotAverageFromTE(TE, trialSets, 1,...
    'zeroTimes', TE.usZeros, 'FluorDataField', fdField, 'window', window, 'linespec', {'b', 'c', 'k'}, 'alpha', 1); % cued reward
addStimulusPatch(gca, [-2 -1], '', [0.7 0.7 0.7], 0.4);  addStimulusPatch(gca, [-0.1 0.1], '', [0.7 0.7 0.7], 0.4);
formatFigurePublish('size', figSize);