function makeSpineAnalysisFigures
global gh

gh.spineGUI.initFigure=figure('NumberTitle', 'off', 'Name', 'Top Spine Analysis Image', 'DoubleBuffer', 'on', ...
		'Pointer', 'arrow', 'Position', [ 6   559   412   412], ...
		'Visible', 'off', 'CloseRequestFcn', 'set(gcf, ''Visible'', ''off'')', 'KeyPressFcn', 'spineKeyPress');
colormap(makeColorMap('gray',8));

gh.spineGUI.initialaxis=axes('Ydir', 'reverse','Parent', gh.spineGUI.initFigure, 'DataAspectRatioMode', ...
	'manual', 'YTickLabelMode', 'manual',  'XTickLabelMode', 'manual', 'XTickLabel', [] , 'YTickLabel', [], 'Position', [0 0 1 1]);

gh.spineGUI.initFigure2=figure('NumberTitle', 'off', 'Name', 'Bottom Spine Analysis Image', 'DoubleBuffer', 'on', ...
		'Pointer', 'arrow', 'Position', [7    74   412   412], ...
		'Visible', 'off', 'CloseRequestFcn', 'set(gcf, ''Visible'', ''off'')', 'KeyPressFcn', 'spineKeyPress');
colormap(makeColorMap('gray',8));

gh.spineGUI.initialaxis2=axes('Ydir', 'reverse','Parent', gh.spineGUI.initFigure2, 'DataAspectRatioMode', ...
	'manual', 'YTickLabelMode', 'manual',  'XTickLabelMode', 'manual', 'XTickLabel', [] , 'YTickLabel', [], 'Position', [0 0 1 1]);

gh.spineGUI.mainFigure=figure('NumberTitle', 'off', 'Name', 'Spine Analysis Image', 'DoubleBuffer', 'on', ...
		'Pointer', 'arrow', 'Position', [426   363   600   600], ...
		'Visible', 'off', 'CloseRequestFcn', 'set(gcf, ''Visible'', ''off'')', 'KeyPressFcn', 'spineKeyPress');
colormap(makeColorMap('gray',8));

gh.spineGUI.mainAxes=axes('Ydir', 'reverse','Parent', gh.spineGUI.mainFigure, 'DataAspectRatioMode', ...
	'manual', 'YTickLabelMode', 'manual', 'XTickLabelMode', 'manual', 'XTickLabel', [] , 'YTickLabel', [], 'Position', [0 0 1 1]);

gh.spineGUI.previewFigure=figure('NumberTitle', 'off', 'Name', 'Preview Image', 'DoubleBuffer', 'on', ...
		'Pointer', 'arrow', 'Position', [  1034  699   238  236], ...
		'Visible', 'off', 'CloseRequestFcn', 'set(gcf, ''Visible'', ''off'')');

gh.spineGUI.previewaxis=axes('Ydir', 'reverse','Parent', gh.spineGUI.previewFigure, 'DataAspectRatioMode', ...
	'manual', 'YTickLabelMode', 'manual',  'XTickLabelMode', 'manual', 'XTickLabel', [] , 'YTickLabel', [], 'Position', [0 0 1 1]);

state.imageProc.spine.mainImage = image('CDataMapping', 'scaled','Parent', gh.spineGUI.mainAxes, 'CData', ones(512,512));
