function saveUncageInfo(posNum)
	
	global state
	
	try
		if size(state.internal.uncageInfo,2)~=19
			state.internal.uncageInfo=repmat(-1,1,19);
		end
	catch
		state.internal.uncageInfo=repmat(-1,1,19);
	end
	
	try
		turnOffMotorButtons;
		definePosition(posNum);
	catch
	end
	turnOnMotorButtons;	
	
	relevantInfo=[...
			state.acq.zoomFactor ...
			state.acq.scanRotation ...
			state.acq.postRotOffsetX ...
			state.acq.postRotOffsetY...
			state.blaster.XList(1) ...
			state.blaster.YList(1) ...
			state.blaster.indexXList(1) ...
			state.blaster.indexYList(1) ...
			state.blaster.indexList(1) ...
			state.blaster.allConfigs{2, 2}(1, 3) ... % state.blaster.lineWidth;
			state.blaster.allConfigs{2, 2}(1, 4) ... % state.blaster.linePower1;
			state.blaster.allConfigs{2, 2}(1, 5) ... % state.blaster.linePower2;
			state.internal.trackerX0 ...
			state.internal.trackerY0 ...
			state.acq.scanShiftX ...
			state.acq.scanShiftY ...
			state.acq.pixelShiftX ...
			state.acq.pixelShiftY ...
			state.internal.refShiftX ...
			state.internal.refShiftY ...
		];

	state.internal.uncageInfo(posNum, :)=relevantInfo;
	state.internal.trackerReferences{posNum} = state.acq.trackerReference;
	state.acq.trackerReferencesAll{posNum} = state.acq.trackerReferenceAll;	
	disp(['*** SAVED TO POSITION ' num2str(posNum) ]);
	