function mcMakeChannelPlots
    global state
    
    if ishandle(state.phys.mcAcq.mcFigure)
        clf(state.phys.mcAcq.mcFigure);
    else
        state.phys.mcAcq.mcFigure = figure(...
            'doublebuffer', 'on',...
            'KeyPressFcn', 'mcFigureKeyPressFunction',...
            'Tag', 'mcFigure',...
            'Name', 'mcFigure',...
            'MenuBar', 'figure',...
            'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')'...
            );
    end
    validChannels=find(mcChannelFieldToVector('mcFigureInclude'));
    state.phys.mcAcq.displayedChannels = validChannels;
    nValidChannels = length(validChannels);
    gap=.005;
    start=.05;
    height = 1 - start*2;
    delta=(height-gap*(nValidChannels-1))/nValidChannels;    
    start = 1 - delta - start;
    

    state.phys.mcAcq.axes = zeros(1, nValidChannels) + -1;
    state.phys.mcAcq.lines = zeros(1, nValidChannels) + -1;


% Plot multichannel channels selected for display
    for i = 1:nValidChannels
        channel = validChannels(i);
        state.phys.mcAcq.axes(1, i) = axes(...
            'NextPlot', 'add',...
            'Parent', state.phys.mcAcq.mcFigure,...
            'Xtick', [],...
            'XTickLabel', {''}...
            );
%         startX = state.mcViewer.startX;
%         deltaX = 1/state.mcViewer.sampleRate;
%         endX = state.mcViewer.startX + deltaX * (size(state.mcViewer.displayData, 2)-1);
        state.phys.mcAcq.lines(1, i) = line(...
            state.phys.mcAcq.displayXData, ... % xdata scaled appropriately
            state.phys.mcAcq.displayData(:, channel),... % ydata FS MOD
            'Parent', state.phys.mcAcq.axes(1, i)...
            );
        set(state.phys.mcAcq.axes(1, i), ...
            'Xtick', [],...
            'XTickLabel', {''},...
            'Position', [.1 start - (i - 1) * (delta + gap) .8 delta]...
            );
        ylabel(state.phys.mcAcq.axes(1, i), state.phys.mcAcq.channel(channel).Name);
        if i == nValidChannels
            set(state.phys.mcAcq.axes(1, i), 'XTickMode', 'auto', 'XTickLabelMode', 'auto');
        end        
    end

            