function fsSaveSliceInSeries(chan, slice)
	if nargin<1
		chan=1;
	end

	if nargin<2
		slice=1;
	end
	
	
	
	
	global state

	axisPosition = [0 0 1 1];
	aspectRatio = state.internal.imageAspectRatioBias*state.acq.scanAmplitudeY/state.acq.scanAmplitudeX; 
		
	for channelCounter = chan
		low = getfield(state.internal, ['lowPixelValue' num2str(channelCounter)]);
		high = getfield(state.internal, ['highPixelValue' num2str(channelCounter)]);
		
		thisFigure = figure(...
			'Position', eval(['state.windowPositions.image' num2str(channelCounter) '_position']), ...
			'doublebuffer', 'on',...
			'KeyPressFcn', 'genericKeyPressFunction', ...
			'Tag',  ['GraphFigure' num2str(channelCounter)], ...
			'Name',  ['Saved Channel ' num2str(channelCounter) ' acq ' num2str(state.files.fileCounter-1) ' slice ' num2str(slice)], ...
			'NumberTitle', 'off',  ...
			'MenuBar', 'figure', ...
			'CloseRequestFcn', 'set(gcf, ''visible'', ''off'')', ...
			'visible', 'on', ...
			'ColorMap', makeColorMap('graySat',8) ...
			);
		
		thisAxis = axes(...
			'YDir', 'Reverse', ...
			'NextPlot', 'add', ...
			'XLim', [0 state.acq.pixelsPerLine], ...
			'YLim', [0 state.acq.linesPerFrame], ...
			'CLim', [low high], ...
			'Parent', thisFigure, ...
			'YTickLabelMode', 'manual', ...
			'XTickLabelMode', 'manual', ...
			'Position', axisPosition,  ...
			'XTickLabel', [], ...
			'YTickLabel', [], ...
			'DataAspectRatioMode', 'manual',  ...
			'DataAspectRatio', [aspectRatio 1 1], ...
			'ButtonDownFcn', 'figureButtonOverCallback'...
			);
		
		thisImage = image(...
			state.acq.acquiredData{channelCounter}(:,:,slice), ...
			'CDataMapping', 'Scaled', ...
			'Parent', thisAxis, ...
			'ButtonDownFcn', 'figureButtonOverCallback'...
			);
	end
